### PR TITLE
refactored header and footer to support landing pages

### LINKED ISSUE #88: Head/Footer for landing pages
Landing pages have a different header and footer.

Need to add these and give the author (probably based on a theme property) the ability to select that header/footer to be used.

example: https://www.surest.com/intro

### PR DESCRIPTION
**Pull request by shsteimer**
Fix #88 

Test URLs:
- Before: https://main--uhg-surest--hlxsites.hlx.page/accenture
- Before: https://main--uhg-surest--hlxsites.hlx.live
- After: https://landing-pages--uhg-surest--hlxsites.hlx.page/accenture
- After: https://landing-pages--uhg-surest--hlxsites.hlx.live

### CODE REVIEW

**Comment by shsteimer** [comment]
FWIW, I don't think there is any way to get to 100 page speed. with that Accenture page as is because of the above the fold video embed. Need to look at some options for fixing this

**Comment by qilto** [comment]
Some of the styling is a bit off on the default footer, mostly around the buttons and social icons.

**Comment by badvision** [comment]
Will approve once conflicts with header are resolved and we can see breadcrumb still works.

**Review by badvision — APPROVED** [review]
Looks fine, but we need to fix the merge conflict and ensure header still has working breadcrumbs after resolving.

**Pull request merged**
